import { Pathway_Extreme } from "next/font/google"
import background from "./assets/background.webp"
import "./style.css"

const font = Pathway_Extreme({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-gray-950 text-gray-100">
      <body className={font.className}>
        <div
          className="fixed inset-0 brightness-[0.2] bg-cover bg-center"
          style={{ backgroundImage: `url(${background.src})` }}
        />
          <div className="min-h-screen flex flex-col relative">{children}</div>
      </body>
    </html>
  )
}
